workflows:
  ios-release:
    name: iOS release build
    instance_type: mac_mini_m1
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Install dependencies
        script: |
          flutter packages pub get
      - name: Force Podfile generation and set platform
        script: |
          cd ios
          pod init
          sed -i '' 's/# platform :ios, '\''12.0\''/platform :ios, '\''15.5\''/g' Podfile
          cd ..
      - name: Build iOS unsigned ipa via Payload
        script: |
          flutter build ios --release --no-codesign
          
          # Masuk ke folder hasil build
          cd build/ios/iphoneos
          
          # Buat struktur Payload
          mkdir -p Payload
          
          # Pindahkan Runner.app ke dalam Payload
          mv Runner.app Payload/
          
          # Zip struktur tersebut menjadi IPA dan pastikan posisinya bisa dibaca artifacts
          zip -qr ../AndalanTools.ipa Payload
          
          # Debug output untuk melihat di mana file ipa-nya berada
          cd ../../..
          ls -la build/ios/
    artifacts:
      - build/ios/AndalanTools.ipa


